language: node_js
node_js:
  - 16
dist: focal
install:
  - npm i -g markbind-cli
script: markbind build
deploy:
  provider: script
  script: markbind deploy --ci
  skip_cleanup: true
  on:
    branch: main